# Generated by Django 3.2.5 on 2021-09-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
